require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# Each extension has it's cops in it's own config file
inherit_from:
  - performance.yml
  - rails.yml
  - rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb

# Lint

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

# Layout

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/FirstMethodArgumentLineBreak:
  AllowMultilineFinalElement: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# Style

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - db/**/*

Style/IfUnlessModifier:
  Exclude:
    - config/**/*

Style/Documentation:
  Enabled: false

# Metrics

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

RSpec/MultipleMemoizedHelpers:
  Max: 8
