# Seperate config file for the rubocop-rspec cops

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Enabled: false
