name: RubyGems Deployment

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install
    - name: Publish to RubyGems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        gem build paperkite-rubocop.gemspec
        gem push paperkite-rubocop-*.gem
