name: RubyGems Deployment

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
    - uses: rubygems/release-gem@v1
